package com.github.estebangmz666.model;

public enum Category {
    DEPOSITO,
    RETIRO,
    ALIMENTACION,
    TECNOLOGIA,
    PAGO_DE_SERVICIOS,
    TRANSPORTE,
    SALUD,
    EDUCACION,
    VIVIENDA,
    OCIO_Y_ENTRETENIMIENTO,
    AHORRO_E_INVERSIONES,
    DONACIONES,
    ROPA_Y_CALZADO,
    SEGUROS,
    VIAJES_Y_TURISMO,
    REGALOS_Y_COMPRAS_PERSONALES,
    GASTOS_GENERALES
}